<?php

declare(strict_types=1);

namespace App\Message;

/**
 * Encodes and decodes the messages send via symfony messenger, which the publish API enqueues.
 * It declares the same namespace, class name and property names:
 * Messenger picks the target class from the message's `type` header
 * ("App\Message\BuildJob"), then the serializer maps JSON keys onto constructor parameter names,
 * so a mismatch on either breaks decoding.
 * publish validates every field before enqueueing, so the worker uses them unchecked.
 *
 * @param string $build_id Per-build UUID v7 generated by the publish API, names the job's folder under JOB_STORAGE_DIR.
 * @param string $static_site_id Main identifier of a site, names the site's directory under PUBLISHED_DIR.
 * @param string $slug Names the published directory under PUBLISHED_DIR/<static_site_id> which translates to the uri path of the published site.
 * @param string $content_download_url Download url for the build assets
 * @param string $callback_status_url Callback url to update the build status
 * @param string $created_at Timestamp when the job was created by the publish API.
 * @param string $title Site title, shown in the page header.
 */
final class BuildJob
{
    public function __construct(
        public readonly string $build_id,
        public readonly string $static_site_id,
        public readonly string $slug,
        public readonly string $content_download_url,
        public readonly string $callback_status_url,
        public readonly string $created_at,
        public readonly string $title,
    ) {
    }
}
